# Clustering Section

## 0. Data Prep

In [2]:
import pandas as pd

df = pd.read_csv('../Data/entertainment_clean.csv')
df.head()

      name  books  tv_shows  video_games
0  Aaliyah    0.5       4.6          4.9
1  Abigail    0.0       4.5          4.8
2  Addison    0.5       4.5          5.0
3  Adeline    3.5       4.5          6.6
4    Alana    2.8       3.8          5.6

In [ ]:
# checks
# 1. row granularity
# 2. columns non-null
# 3. columns numberic
# 4. feature engineering
# 5. feature selection
# 6. feature scaling

In [3]:
df.shape

(150, 4)

In [6]:
df.name.nunique()

150

In [9]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [name, books, tv_shows, video_games]
Index: []

In [12]:
df.head()

      name  books  tv_shows  video_games
0  Aaliyah    0.5       4.6          4.9
1  Abigail    0.0       4.5          4.8
2  Addison    0.5       4.5          5.0
3  Adeline    3.5       4.5          6.6
4    Alana    2.8       3.8          5.6

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         150 non-null    object
 1   books        150 non-null    float64
 2   tv_shows     150 non-null    float64
 3   video_games  150 non-null    float64
dtypes: float64(3), object(1)
memory usage: 4.8+ KB

In [13]:
name = df.name

In [14]:
data = df.drop(columns=['name'])

In [15]:
data

     books  tv_shows  video_games
0      0.5       4.6          4.9
1      0.0       4.5          4.8
2      0.5       4.5          5.0
3      3.5       4.5          6.6
4      2.8       3.8          5.6
..     ...       ...          ...
145    5.2       4.6          6.9
146    6.0       4.6          6.7
147    5.5       5.7          7.7
148    0.0       6.1          5.2
149    1.2       4.9          5.1

[150 rows x 3 columns]

In [16]:
data.describe()

            books    tv_shows  video_games
count  150.000000  150.000000   150.000000
mean     2.993333    4.586000     5.843333
std      1.917761    0.645587     0.828066
min      0.000000    3.000000     4.300000
25%      0.800000    4.200000     5.100000
50%      3.200000    4.500000     5.800000
75%      4.500000    4.900000     6.400000
max      6.200000    6.600000     7.900000

In [17]:
data.head()

   books  tv_shows  video_games
0    0.5       4.6          4.9
1    0.0       4.5          4.8
2    0.5       4.5          5.0
3    3.5       4.5          6.6
4    2.8       3.8          5.6

## 1. Kmean

In [18]:
from sklearn.cluster import KMeans

In [19]:
kmeans2 = KMeans(n_clusters=2, n_init='auto', random_state=42)

In [20]:
kmeans2.fit(data)

KMeans(n_clusters=2, random_state=42)

In [21]:
kmeans2.labels_

array([0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0], dtype=int32)